import { ThemeConfig, ThemeId } from '../types';

export const THEMES: Record<ThemeId, ThemeConfig> = {
  'pure-black': {
    id: 'pure-black',
    name: 'Pure Black',
    tagline: 'Static AMOLED • Clean & Distraction-Free',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-black text-white',
    cardClass: 'bg-zinc-950/80 border border-zinc-900',
    borderClass: 'border-zinc-900',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-zinc-400 text-xs',
    accentClass: 'bg-cyan-400 text-black hover:bg-cyan-300 font-bold',
    accentGradient: 'from-cyan-400 to-blue-500 text-black',
    glowClass: 'shadow-none',
    bottomNavClass: 'bg-black/95 border-t border-zinc-900',
    headerClass: 'bg-black/95 border-b border-zinc-900',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-zinc-900 text-zinc-300 border border-zinc-800 hover:border-zinc-700',
    viewerBg: 'bg-black',
    playerAccent: '#00f3ff',
    previewGradient: 'bg-black border border-zinc-800',
  },
  'pure-white': {
    id: 'pure-white',
    name: 'Pure White',
    tagline: 'Bright & Clean • Minimal Focus',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-white text-zinc-900',
    cardClass: 'bg-zinc-900/90 border border-zinc-800 text-white',
    borderClass: 'border-zinc-300',
    textPrimaryClass: 'text-zinc-900 font-bold',
    textSecondaryClass: 'text-zinc-600 text-xs',
    accentClass: 'bg-cyan-500 text-white hover:bg-cyan-600 font-bold',
    accentGradient: 'from-cyan-500 to-blue-600 text-white',
    glowClass: 'shadow-sm',
    bottomNavClass: 'bg-white/95 border-t border-zinc-200 text-zinc-900',
    headerClass: 'bg-white/95 border-b border-zinc-200 text-zinc-900',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-zinc-100 text-zinc-800 border border-zinc-300 hover:bg-zinc-200',
    viewerBg: 'bg-white',
    playerAccent: '#0284c7',
    previewGradient: 'bg-white border border-zinc-300',
  },
  'obsidian': {
    id: 'obsidian',
    name: 'Obsidian',
    tagline: 'Smoked Glass • Luxury Dark & Cinematic',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-slate-950/70 border border-slate-800/60 backdrop-blur-xl shadow-[0_10px_30px_rgba(0,0,0,0.6)]',
    borderClass: 'border-slate-800/60',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-slate-400 text-xs',
    accentClass: 'bg-sky-400 text-black hover:bg-sky-300 font-bold',
    accentGradient: 'from-slate-300 via-sky-300 to-slate-400 text-black',
    glowClass: 'shadow-[0_0_20px_rgba(56,189,248,0.1)]',
    bottomNavClass: 'bg-slate-950/90 border-t border-slate-800/60 backdrop-blur-xl',
    headerClass: 'bg-slate-950/90 border-b border-slate-800/60 backdrop-blur-xl',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-slate-900/80 text-slate-200 border border-slate-800 hover:border-slate-600',
    viewerBg: 'bg-black',
    playerAccent: '#38bdf8',
    previewGradient: 'bg-gradient-to-br from-black via-slate-950 to-[#0a0f1e]',
  },
  'ivory': {
    id: 'ivory',
    name: 'Ivory',
    tagline: 'Warm Cream • Minimal & Elegant',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-zinc-900',
    cardClass: 'bg-[#f5efe4]/90 border border-[#e2d5bd] text-zinc-900 shadow-sm',
    borderClass: 'border-[#e2d5bd]',
    textPrimaryClass: 'text-zinc-900 font-bold',
    textSecondaryClass: 'text-[#8a7a5c] text-xs',
    accentClass: 'bg-amber-500 text-white hover:bg-amber-600 font-bold',
    accentGradient: 'from-amber-400 to-amber-600 text-white',
    glowClass: 'shadow-sm',
    bottomNavClass: 'bg-[#faf6ee]/95 border-t border-[#e2d5bd] text-zinc-900',
    headerClass: 'bg-[#faf6ee]/95 border-b border-[#e2d5bd] text-zinc-900',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-[#efe6d3] text-zinc-800 border border-[#ddd0b3] hover:bg-[#e6dabf]',
    viewerBg: 'bg-[#f5efe4]',
    playerAccent: '#d97706',
    previewGradient: 'bg-gradient-to-br from-[#faf6ee] via-[#f2e9d8] to-[#e9dcc0]',
  },
  'sapphire': {
    id: 'sapphire',
    name: 'Sapphire',
    tagline: 'Royal Blue • Modern & Futuristic',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-blue-950/75 border border-blue-800/40 backdrop-blur-md shadow-md',
    borderClass: 'border-blue-800/40',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-blue-300/70 text-xs',
    accentClass: 'bg-blue-400 text-black hover:bg-blue-300 font-bold',
    accentGradient: 'from-blue-400 via-blue-500 to-indigo-500 text-white',
    glowClass: 'shadow-[0_0_20px_rgba(59,130,246,0.15)]',
    bottomNavClass: 'bg-blue-950/90 border-t border-blue-900/50 backdrop-blur-md',
    headerClass: 'bg-blue-950/90 border-b border-blue-900/50 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-blue-900/60 text-blue-100 border border-blue-800 hover:border-blue-500/50',
    viewerBg: 'bg-blue-950',
    playerAccent: '#60a5fa',
    previewGradient: 'bg-gradient-to-br from-[#050b24] via-[#0b1a4a] to-[#132a6b]',
  },
  'emerald': {
    id: 'emerald',
    name: 'Emerald',
    tagline: 'Forest Green • Calm & Sophisticated',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-emerald-950/75 border border-emerald-800/40 backdrop-blur-md shadow-md',
    borderClass: 'border-emerald-800/40',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-emerald-300/70 text-xs',
    accentClass: 'bg-emerald-400 text-black hover:bg-emerald-300 font-bold',
    accentGradient: 'from-emerald-400 via-green-500 to-emerald-600 text-black',
    glowClass: 'shadow-[0_0_20px_rgba(16,185,129,0.12)]',
    bottomNavClass: 'bg-emerald-950/90 border-t border-emerald-900/50 backdrop-blur-md',
    headerClass: 'bg-emerald-950/90 border-b border-emerald-900/50 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-emerald-900/60 text-emerald-100 border border-emerald-800 hover:border-emerald-500/50',
    viewerBg: 'bg-emerald-950',
    playerAccent: '#34d399',
    previewGradient: 'bg-gradient-to-br from-[#04140d] via-[#062919] to-[#0a3d24]',
  },
  'crimson': {
    id: 'crimson',
    name: 'Crimson',
    tagline: 'Deep Burgundy • Bold & Cinematic',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-red-950/75 border border-red-900/40 backdrop-blur-md shadow-md',
    borderClass: 'border-red-900/40',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-red-300/70 text-xs',
    accentClass: 'bg-red-400 text-black hover:bg-red-300 font-bold',
    accentGradient: 'from-red-500 via-rose-600 to-red-800 text-white',
    glowClass: 'shadow-[0_0_20px_rgba(239,68,68,0.12)]',
    bottomNavClass: 'bg-red-950/90 border-t border-red-900/50 backdrop-blur-md',
    headerClass: 'bg-red-950/90 border-b border-red-900/50 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-red-950/70 text-red-100 border border-red-900 hover:border-red-600/50',
    viewerBg: 'bg-red-950',
    playerAccent: '#f87171',
    previewGradient: 'bg-gradient-to-br from-[#150406] via-[#2c0a0f] to-[#3d0f16]',
  },
  'desert-sand': {
    id: 'desert-sand',
    name: 'Desert Sand',
    tagline: 'Warm Beige • Earthy & Editorial',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-[#4a3c28]',
    cardClass: 'bg-[#e8dcc4]/85 border border-[#d3c19d] text-[#4a3c28] shadow-sm',
    borderClass: 'border-[#d3c19d]',
    textPrimaryClass: 'text-[#4a3c28] font-bold',
    textSecondaryClass: 'text-[#8a7150] text-xs',
    accentClass: 'bg-orange-500 text-white hover:bg-orange-600 font-bold',
    accentGradient: 'from-orange-400 to-amber-600 text-white',
    glowClass: 'shadow-sm',
    bottomNavClass: 'bg-[#efe4cd]/95 border-t border-[#d3c19d] text-[#4a3c28]',
    headerClass: 'bg-[#efe4cd]/95 border-b border-[#d3c19d] text-[#4a3c28]',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-[#ddcfae] text-[#4a3c28] border border-[#c9b98e] hover:bg-[#d3c19d]',
    viewerBg: 'bg-[#e8dcc4]',
    playerAccent: '#c2621b',
    previewGradient: 'bg-gradient-to-br from-[#efe4cd] via-[#e3d3ab] to-[#d3bd8b]',
  },
  'arctic': {
    id: 'arctic',
    name: 'Arctic',
    tagline: 'Frosted Glass • Cool & Futuristic',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-slate-800',
    cardClass: 'bg-white/60 border border-sky-100 backdrop-blur-xl text-slate-800 shadow-sm',
    borderClass: 'border-sky-100',
    textPrimaryClass: 'text-slate-800 font-bold',
    textSecondaryClass: 'text-slate-500 text-xs',
    accentClass: 'bg-sky-400 text-white hover:bg-sky-500 font-bold',
    accentGradient: 'from-sky-300 to-blue-400 text-white',
    glowClass: 'shadow-sm',
    bottomNavClass: 'bg-white/70 border-t border-sky-100 backdrop-blur-xl text-slate-800',
    headerClass: 'bg-white/70 border-b border-sky-100 backdrop-blur-xl text-slate-800',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-sky-50/80 text-slate-700 border border-sky-100 hover:bg-sky-100/80',
    viewerBg: 'bg-slate-50',
    playerAccent: '#38bdf8',
    previewGradient: 'bg-gradient-to-br from-white via-sky-50 to-[#dceaf5]',
  },
  'violet-noir': {
    id: 'violet-noir',
    name: 'Violet Noir',
    tagline: 'Deep Plum • Elegant & Mysterious',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-violet-950/75 border border-violet-900/40 backdrop-blur-md shadow-md',
    borderClass: 'border-violet-900/40',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-violet-300/60 text-xs',
    accentClass: 'bg-violet-400 text-black hover:bg-violet-300 font-bold',
    accentGradient: 'from-violet-400 via-purple-500 to-fuchsia-600 text-white',
    glowClass: 'shadow-[0_0_20px_rgba(167,139,250,0.12)]',
    bottomNavClass: 'bg-violet-950/90 border-t border-violet-900/50 backdrop-blur-md',
    headerClass: 'bg-violet-950/90 border-b border-violet-900/50 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-violet-950/70 text-violet-100 border border-violet-900 hover:border-violet-600/50',
    viewerBg: 'bg-violet-950',
    playerAccent: '#a78bfa',
    previewGradient: 'bg-gradient-to-br from-[#0e0616] via-[#1e0e2e] to-[#2b1440]',
  },
  'copper-forge': {
    id: 'copper-forge',
    name: 'Copper Forge',
    tagline: 'Brushed Metal • Industrial Luxury',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-[#e8d9c8]',
    cardClass: 'bg-[#241a14]/85 border border-[#4a3626]/70 backdrop-blur-md shadow-md text-[#e8d9c8]',
    borderClass: 'border-[#4a3626]/70',
    textPrimaryClass: 'text-[#f0e2d0] font-bold',
    textSecondaryClass: 'text-[#b08a63] text-xs',
    accentClass: 'bg-orange-600 text-white hover:bg-orange-500 font-bold',
    accentGradient: 'from-amber-600 via-orange-700 to-[#8a4a1e] text-white',
    glowClass: 'shadow-[0_0_20px_rgba(201,117,47,0.12)]',
    bottomNavClass: 'bg-[#1c130e]/95 border-t border-[#4a3626]/70 backdrop-blur-md',
    headerClass: 'bg-[#1c130e]/95 border-b border-[#4a3626]/70 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-[#2c2018]/90 text-[#d9c2a6] border border-[#4a3626] hover:border-[#7a4b28]',
    viewerBg: 'bg-[#1c130e]',
    playerAccent: '#c9752f',
    previewGradient: 'bg-gradient-to-br from-[#160f0b] via-[#2a1c12] to-[#3d2818]',
  },
  'ocean-deep': {
    id: 'ocean-deep',
    name: 'Ocean Deep',
    tagline: 'Marine Teal • Calm & Immersive',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-teal-950/75 border border-teal-800/40 backdrop-blur-md shadow-md',
    borderClass: 'border-teal-800/40',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-teal-300/60 text-xs',
    accentClass: 'bg-teal-400 text-black hover:bg-teal-300 font-bold',
    accentGradient: 'from-sky-500 via-teal-500 to-cyan-600 text-white',
    glowClass: 'shadow-[0_0_20px_rgba(45,212,191,0.12)]',
    bottomNavClass: 'bg-teal-950/90 border-t border-teal-900/50 backdrop-blur-md',
    headerClass: 'bg-teal-950/90 border-b border-teal-900/50 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-teal-950/70 text-teal-100 border border-teal-900 hover:border-teal-600/50',
    viewerBg: 'bg-teal-950',
    playerAccent: '#2dd4bf',
    previewGradient: 'bg-gradient-to-br from-[#031014] via-[#062733] to-[#0a3d4a]',
  },
  'rose-marble': {
    id: 'rose-marble',
    name: 'Rose Marble',
    tagline: 'Dusty Blush • Elegant & Architectural',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-[#5c4a4a]',
    cardClass: 'bg-[#f2e4e2]/80 border border-[#e0c9c6] text-[#5c4a4a] shadow-sm',
    borderClass: 'border-[#e0c9c6]',
    textPrimaryClass: 'text-[#5c4a4a] font-bold',
    textSecondaryClass: 'text-[#a1817e] text-xs',
    accentClass: 'bg-rose-400 text-white hover:bg-rose-500 font-bold',
    accentGradient: 'from-rose-300 to-[#c99a97] text-white',
    glowClass: 'shadow-sm',
    bottomNavClass: 'bg-[#f7ecea]/90 border-t border-[#e0c9c6] text-[#5c4a4a]',
    headerClass: 'bg-[#f7ecea]/90 border-b border-[#e0c9c6] text-[#5c4a4a]',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-[#ecdad7] text-[#5c4a4a] border border-[#ddc2be] hover:bg-[#e5cdc9]',
    viewerBg: 'bg-[#f2e4e2]',
    playerAccent: '#c9827c',
    previewGradient: 'bg-gradient-to-br from-[#faf3f1] via-[#f0dcd9] to-[#e3c5c1]',
  },
  'carbon': {
    id: 'carbon',
    name: 'Carbon',
    tagline: 'Carbon Fiber • Technical & Automotive',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-transparent text-zinc-100',
    cardClass: 'bg-zinc-900/80 border border-zinc-700/60 backdrop-blur-md shadow-md',
    borderClass: 'border-zinc-700/60',
    textPrimaryClass: 'text-zinc-100 font-bold',
    textSecondaryClass: 'text-zinc-400 text-xs',
    accentClass: 'bg-red-500 text-white hover:bg-red-400 font-bold',
    accentGradient: 'from-zinc-400 via-zinc-500 to-zinc-700 text-white',
    glowClass: 'shadow-[0_0_15px_rgba(239,68,68,0.1)]',
    bottomNavClass: 'bg-zinc-950/95 border-t border-zinc-800 backdrop-blur-md',
    headerClass: 'bg-zinc-950/95 border-b border-zinc-800 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-zinc-800/80 text-zinc-200 border border-zinc-700 hover:border-zinc-500',
    viewerBg: 'bg-zinc-950',
    playerAccent: '#ef4444',
    previewGradient: 'bg-gradient-to-br from-[#0a0a0c] via-[#161619] to-[#242428]',
  },
};

export const DEFAULT_THEME_ID: ThemeId = 'pure-black';

export function getThemeConfig(themeId?: string): ThemeConfig {
  if (themeId && themeId in THEMES) {
    return THEMES[themeId as ThemeId];
  }
  return THEMES[DEFAULT_THEME_ID];
}
